name: test e2e
on:
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        # if: ${{ contains(cypress.config.js,projectId) }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          command: npm run test:cloud
